cluster:
    max_workers: 1
    method: null
device: gpu
microscope:
    beam:
        acceleration_voltage_spread: 8.0e-07
        drift:
            magnitude: 0
            type: null
        electrons_per_angstrom: 30
        energy: 300
        energy_spread: 2.66e-06
        source_spread: 0.1
    detector:
        dqe: false
        nx: 512
        ny: 512
        origin:
        - 256
        - 256
        pixel_size: 1
    model: null
    objective_lens:
        c_10: -20000
        c_12: 0.0
        c_21: 0.0
        c_23: 0.0
        c_30: 2.7
        c_32: 0.0
        c_34: 0.0
        c_41: 0.0
        c_43: 0.0
        c_45: 0.0
        c_50: 0.0
        c_52: 0.0
        c_54: 0.0
        c_56: 0.0
        c_c: 2.7
        current_spread: 3.3e-07
        inner_aper_ang: 0.0
        m: 0
        outer_aper_ang: 0.0
        phi_12: 0.0
        phi_21: 0.0
        phi_23: 0.0
        phi_32: 0.0
        phi_34: 0.0
        phi_41: 0.0
        phi_43: 0.0
        phi_45: 0.0
        phi_52: 0.0
        phi_54: 0.0
        phi_56: 0.0
    phase_plate: false
sample:
    box:
    - 1024
    - 1024
    - 1024
    centre:
    - 512
    - 512
    - 512
    coords:
        filename: trajectory/6vxx.pdb
        recentre: true
    ice:
        density: 940
        generate: false
    molecules:
        4v1w: 0
        4v5d: 0
        6qt9: 0
        6z6u: 0
    shape:
        cube:
            length: 1024
        cuboid:
            length_x: 4000
            length_y: 4000
            length_z: 4000
        cylinder:
            length: 10000
            radius: 1500
        margin:
        - 0
        - 0
        - 0
        type: cube
    sputter:
        element: null
        thickness: 20
scan:
    axis:
    - 0
    - 1
    - 0
    exposure_time: 1
    mode: still
    num_images: 1
    start_angle: 0
    start_pos: 0
    step_angle: 10
    step_pos: auto
simulation:
    division_thickness: 100
    ice: true
    inelastic_model: null
    margin: 100
    mp_loss_position: peak
    mp_loss_width: null
    padding: 100
    radiation_damage_model: false
    sensitivity_coefficient: 0.014
    slice_thickness: 3.0

